### ISSUE TITLE
[EPIC] Error Checking

### ISSUE THREAD

**Issue by jonLicari** [jonLicari/learning-vault#21]
- [ ] Make notes on Ben Eater videos on YouTube
- [ ] Create CRC HW Accelerator demo on STM32 
- [ ] Add my notes on CRC to the vault
- [ ] HW Accelerated vs SW performance demo STM32
- [ ] Encryption in embedded devices
- [ ] parity check digital design
- [ ] parity check notes
