### ISSUE TITLE
[EPIC] RTOS

### ISSUE THREAD

**Issue by jonLicari** [jonLicari/learning-vault#22]
- [ ] POSIX ELE-709 notes
- [ ] ELE-709 Lab 5
- [ ] OS Threads COE-718
- [ ] Shawn Hymel RTOS series part 1
- [ ] Shawn Hymel RTOS series part 2
